FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt /app
RUN apt update &&\
    apt install -y build-essential gcc &&\
    pip install --no-cache-dir -r requirements.txt

COPY . /app

EXPOSE 8501

ENTRYPOINT [ "sleep", "3600" ]
