services:
  source_db:
    image: postgres:latest
    container_name: source_DB
    environment:
      - POSTGRES_DB=${SOURCE_DB}
      - POSTGRES_USER=${SOURCE_USER}
      - POSTGRES_PASSWORD=${SOURCE_PASSWORD}
    volumes:
      - source_data:/var/lib/postgresql/data
      - ./scripts/init-script.sql:/docker-entrypoint-initdb.d/init-script.sql
      - ./scripts/inject_data.sh:/scripts/inject_data.sh
      - ./data:/psql_data
    ports:
      - "5434:5432"
  
  target_db:
    image: postgres:latest
    container_name: target_DB
    environment: 
      - POSTGRES_DB=${TARGET_DB}
      - POSTGRES_USER=${TARGET_USER}
      - POSTGRES_PASSWORD=${TARGET_PASSWORD}
    volumes:
      - target_data:/var/lib/postgresql/data
      - ./scripts/target_table.sql:/scripts/create_table.sql
    ports:
      - "5433:5432"

volumes:
  source_data:
  target_data:
  
