networks:
  pipeline_network:
    driver: bridge

services:
  source_db:
    image: postgres:latest
    container_name: source_DB
    environment:
      - POSTGRES_DB=${SOURCE_DB}
      - POSTGRES_USER=${SOURCE_USER}
      - POSTGRES_PASSWORD=${SOURCE_PASSWORD}
    volumes:
      - source_data:/var/lib/postgresql/data
      - ./scripts/init-script.sql:/docker-entrypoint-initdb.d/init-script.sql
      - ./scripts/inject_data.sh:/scripts/inject_data.sh
      - ./data:/psql_data
    ports:
      - "5434:5432"
    networks:
      - pipeline_network

  target_db:
    image: postgres:latest
    container_name: target_DB
    environment:
      - POSTGRES_DB=${TARGET_DB}
      - POSTGRES_USER=${TARGET_USER}
      - POSTGRES_PASSWORD=${TARGET_PASSWORD}
    volumes:
      - target_data:/var/lib/postgresql/data
      - ./scripts/create_target_table.sql:/scripts/create_target_table.sql
    ports:
      - "5433:5432"
    networks:
      - pipeline_network

  pipeline:
    build: ./backend/.
    container_name: spark_container
    environment:
      - SOURCE_DB_USER=${SOURCE_USER}
      - SOURCE_DB_PASS=${SOURCE_PASSWORD}
      - TARGET_DB_USER=${TARGET_USER}
      - TARGET_DB_PASS=${TARGET_PASSWORD}
    volumes:
      - ./backend/src_backend:/app/src
    networks:
      - pipeline_network

  frontend:
    build: ./frontend/.
    container_name: frontend
    volumes:
      - ./frontend:/app
    ports:
      - "8501:8501"

volumes:
  source_data:
  target_data:
