FROM apache/spark-py:v3.4.0

USER root

WORKDIR /app

COPY requirements.txt /app

RUN mkdir -p /var/lib/apt/lists/partial && \
    chmod 644 /var/lib/apt/lists/partial && \
    pip install --no-cache-dir -r requirements.txt

ENTRYPOINT [ "sleep", "3600" ]
